name: CI/CD Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          # 必须在这里指定 registry，它会生成一个指向环境变量的 .npmrc
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm install --include=dev --legacy-peer-deps

      - name: Build Library
        run: npm run dist:build

      - name: Publish to NPM
        # 确保 publish 运行在配置了 registry 的环境下
        run: npm publish --access public
        env:
          # 名字必须严格叫 NODE_AUTH_TOKEN
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Build Docs
        run: npm run docs:build

      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
